version: '3'
services: 
    node_app:
        container_name: node_app
        build: .
        command: npm run dev
        ports:
            - "3333:3333"
        volumes: 
            - .:/usr/app
        networks:
            - default

    node_db:
        image: mariadb/server:latest
        container_name: node_db
        restart: unless-stopped
        tty: true
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_DATABASE: api_db
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks: 
            - default
        volumes: 
            - ./docker/mysql:/var/lib/mysql

networks: 
    default:
        driver: bridge

